/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.model.hardware;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Killer Queen
 */
public class FrmCadastro extends javax.swing.JFrame 
{

   
    public FrmCadastro() 
    {
        initComponents();
        setLocationRelativeTo(null);
        
        
        btnClose.setVisible(false);
        
        
        pnList.setVisible(false);
        
        
        lblPesq.setVisible(false);
        txtPesquisa.setVisible(false);
        
        
        txtLista.setVisible(false);
        
        
        btnLimpar.setVisible(false);
        btnListar.setVisible(false);
        btnCrescente.setVisible(false);
        btnDecrescente.setVisible(false);
        btnPesquisar.setVisible(false);
        
       
        pnEdit.setVisible(false);
        
        lblEdit.setVisible(false);
        txtEditar.setVisible(false);
        
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        
        txtLista.setText(bditems.listarHards()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnDecrescente = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnCrescente = new javax.swing.JButton();
        lblPesq = new javax.swing.JLabel();
        btnOptions = new javax.swing.JButton();
        pnEdit = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        txtEditar = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Noto Sans Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        txtItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, 30));

        btnSalvar.setBackground(new java.awt.Color(102, 102, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar item");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 420, 50));

        btnOpen.setBackground(new java.awt.Color(102, 102, 255));
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/r-arrow.png"))); // NOI18N
        btnOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 50));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/d-arrow.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 50));

        pnList.setBackground(new java.awt.Color(0, 102, 102));
        pnList.setForeground(new java.awt.Color(0, 102, 102));
        pnList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        pnList.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 170));

        btnPesquisar.setBackground(new java.awt.Color(102, 102, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar item");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnList.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 50, 50));

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnList.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, 30));

        btnDecrescente.setBackground(new java.awt.Color(102, 102, 255));
        btnDecrescente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descending.png"))); // NOI18N
        btnDecrescente.setToolTipText("Ordem decrescente Z-A");
        btnDecrescente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDecrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrescenteActionPerformed(evt);
            }
        });
        pnList.add(btnDecrescente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 50, 50));

        btnLimpar.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar caixa de texto");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pnList.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 50));

        btnListar.setBackground(new java.awt.Color(102, 102, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
        btnListar.setToolTipText("Listar itens");
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnList.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, 50));

        btnCrescente.setBackground(new java.awt.Color(102, 102, 255));
        btnCrescente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ascending.png"))); // NOI18N
        btnCrescente.setToolTipText("Ordem crescente A-Z");
        btnCrescente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrescenteActionPerformed(evt);
            }
        });
        pnList.add(btnCrescente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 50, 50));

        lblPesq.setFont(new java.awt.Font("Noto Sans Light", 0, 18)); // NOI18N
        lblPesq.setForeground(new java.awt.Color(255, 255, 255));
        lblPesq.setText("Pesquisar:");
        pnList.add(lblPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        jPanel1.add(pnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 420, 250));

        btnOptions.setBackground(new java.awt.Color(102, 102, 255));
        btnOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/options.png"))); // NOI18N
        btnOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(btnOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 50, 50));

        pnEdit.setBackground(new java.awt.Color(102, 102, 102));
        pnEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdit.setBackground(new java.awt.Color(0, 0, 0));
        lblEdit.setFont(new java.awt.Font("Noto Sans Light", 0, 18)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setText("Editar:");
        pnEdit.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        txtEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnEdit.add(txtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, 30));

        btnExcluir.setBackground(new java.awt.Color(102, 102, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir item");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnEdit.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, 50));

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnEdit.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 50));

        jPanel1.add(pnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 420, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static hardware bditems = new hardware(); 
    
    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        btnOpen.setVisible(false);

     
        btnClose.setVisible(true);
        

        pnList.setVisible(true);
        

        lblPesq.setVisible(true);
        txtPesquisa.setVisible(true);
        
   
        txtLista.setVisible(true);
        
 
        btnLimpar.setVisible(true);
        btnListar.setVisible(true);
        btnCrescente.setVisible(true);
        btnDecrescente.setVisible(true);
        btnPesquisar.setVisible(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        btnOpen.setVisible(true);

       
        btnClose.setVisible(false);
        
 
        pnList.setVisible(false);
        
      
        lblPesq.setVisible(false);
        txtPesquisa.setVisible(false);
        
        
        txtLista.setVisible(false);
        
      
        btnLimpar.setVisible(false);
        btnListar.setVisible(false);
        btnCrescente.setVisible(false);
        btnDecrescente.setVisible(false);
        btnPesquisar.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtItem.getText().equals("") || txtItem.getText().equals(null))
        {
            JOptionPane.showMessageDialog(null, "Campo vazio");         
        }
        else
        {
            bditems.adicionar(txtItem.getText());
            
            txtLista.setText(bditems.listarHards()); 
            
            txtItem.setText(null);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtLista.setText(bditems.listarHards()); 
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtLista.setText(null); 
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nome = txtPesquisa.getText(); 
        int i = bditems.pesquisar(nome);
        
        if(i != -1)
        {
            txtLista.setText("Resultado da pesquisa:\n\n=================================\n\n" + (i + 1) + " - " + nome.toUpperCase()); 
            txtPesquisa.setText(null); 
        }
        else if(bditems.returnVazio()) 
        {
            JOptionPane.showMessageDialog(null, "Base vazia"); 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Item nao encontrado"); 
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        if(!bditems.returnVazio()) 
        {
            pnEdit.setVisible(true);
        
            lblEdit.setVisible(true);
            txtEditar.setVisible(true);
        
            btnEditar.setVisible(true);
            btnExcluir.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Base vazia");
        }
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nome = txtEditar.getText().toUpperCase(); 
        int i = bditems.pesquisar(nome);
        String novoNome;
        
        if(i != -1) 
        {
            novoNome = JOptionPane.showInputDialog("Informe o novo nome do item:");
            if(JOptionPane.showConfirmDialog(null, "Editar?", "Editar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                bditems.editar(i, novoNome); 
                JOptionPane.showMessageDialog(null, "Item editado com sucesso");
                txtLista.setText(bditems.listarHards()); 
                txtEditar.setText(null); 
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Edicao cancelada");
            }
        }
        else if(bditems.returnVazio()) 
        {
            JOptionPane.showMessageDialog(null, "Base vazia"); 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Item nao encontrado"); 
        }
        
        pnEdit.setVisible(false);
        
        lblEdit.setVisible(false);
        txtEditar.setVisible(false);
        
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String nome = txtEditar.getText().toUpperCase(); 
        int i = bditems.pesquisar(nome);
        
        if(i != -1) 
        {
            if(JOptionPane.showConfirmDialog(null, "Excluir?", "Exclur?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                bditems.excluir(i); 
                JOptionPane.showMessageDialog(null, "Item excluido com sucesso");
                txtLista.setText(bditems.listarHards()); 
                txtEditar.setText(null); 
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Exclusao cancelada");
            }
        }
        else if(bditems.returnVazio()) 
        {
            JOptionPane.showMessageDialog(null, "Base vazia"); 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Item nao encontrado"); 
        }
        
        pnEdit.setVisible(false);
        
        lblEdit.setVisible(false);
        txtEditar.setVisible(false);
        
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrescenteActionPerformed
        bditems.ordenar();
        txtLista.setText(bditems.listarHards()); 
    }//GEN-LAST:event_btnCrescenteActionPerformed

    private void btnDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrescenteActionPerformed
        bditems.desordenar();
        txtLista.setText(bditems.listarHards()); 
    }//GEN-LAST:event_btnDecrescenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCrescente;
    private javax.swing.JButton btnDecrescente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblPesq;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnList;
    private javax.swing.JTextField txtEditar;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
